ALTER TABLE resident
    ADD COLUMN first_name VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN last_name  VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN gender     VARCHAR(1)   NOT NULL DEFAULT 'M';
